if("undefined"==typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");
(function(b){function g(){var h=document.createElement("bootstrap"),d={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},a;for(a in d)if(void 0!==h.style[a])return{end:d[a]};return false}b.fn.emulateTransitionEnd=function(h){var d=false,a=this;b(this).one("bsTransitionEnd",function(){d=true});return setTimeout(function(){d||b(a).trigger(b.support.transition.end)},h),this};b(function(){b.support.transition=g();
b.support.transition&&(b.event.special.bsTransitionEnd={bindType:b.support.transition.end,delegateType:b.support.transition.end,handle:function(h){return b(h.target).is(this)?h.handleObj.handler.apply(this,arguments):void 0}})})})(jQuery);
(function(b){var g=function(d){b(d).on("click",'[data-dismiss="alert"]',this.close)};g.VERSION="3.2.0";g.prototype.close=function(d){function a(){f.detach().trigger("closed.bs.alert").remove()}var c=b(this),e=c.attr("data-target");e||(e=c.attr("href"),e=e&&e.replace(/.*(?=#[^\s]*$)/,""));var f=b(e);d&&d.preventDefault();f.length||(f=c.hasClass("alert")?c:c.parent());f.trigger(d=b.Event("close.bs.alert"));d.isDefaultPrevented()||(f.removeClass("in"),b.support.transition&&f.hasClass("fade")?f.one("bsTransitionEnd",
a).emulateTransitionEnd(150):a())};var h=b.fn.alert;b.fn.alert=function(d){return this.each(function(){var a=b(this),c=a.data("bs.alert");c||a.data("bs.alert",c=new g(this));"string"==typeof d&&c[d].call(a)})};b.fn.alert.Constructor=g;b.fn.alert.noConflict=function(){return b.fn.alert=h,this};b(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',g.prototype.close)})(jQuery);
(function(b){function g(a){return this.each(function(){var c=b(this),e=c.data("bs.button"),f="object"==typeof a&&a;e||c.data("bs.button",e=new h(this,f));"toggle"==a?e.toggle():a&&e.setState(a)})}var h=function(a,c){this.$element=b(a);this.options=b.extend({},h.DEFAULTS,c);this.isLoading=false};h.VERSION="3.2.0";h.DEFAULTS={loadingText:"loading..."};h.prototype.setState=function(a){var c=this.$element,e=c.is("input")?"val":"html",f=c.data();a+="Text";null==f.resetText&&c.data("resetText",c[e]());
c[e](null==f[a]?this.options[a]:f[a]);setTimeout(b.proxy(function(){"loadingText"==a?(this.isLoading=true,c.addClass("disabled").attr("disabled","disabled")):this.isLoading&&(this.isLoading=false,c.removeClass("disabled").removeAttr("disabled"))},this),0)};h.prototype.toggle=function(){var a=true,c=this.$element.closest('[data-toggle="buttons"]');if(c.length){var e=this.$element.find("input");"radio"==e.prop("type")&&(e.prop("checked")&&this.$element.hasClass("active")?a=false:c.find(".active").removeClass("active"));
a&&e.prop("checked",!this.$element.hasClass("active")).trigger("change")}a&&this.$element.toggleClass("active")};var d=b.fn.button;b.fn.button=g;b.fn.button.Constructor=h;b.fn.button.noConflict=function(){return b.fn.button=d,this};b(document).on("click.bs.button.data-api",'[data-toggle^="button"]',function(a){var c=b(a.target);c.hasClass("btn")||(c=c.closest(".btn"));g.call(c,"toggle");a.preventDefault()})})(jQuery);
(function(b){function g(a){return this.each(function(){var c=b(this),e=c.data("bs.carousel"),f=b.extend({},h.DEFAULTS,c.data(),"object"==typeof a&&a),i="string"==typeof a?a:f.slide;e||c.data("bs.carousel",e=new h(this,f));"number"==typeof a?e.to(a):i?e[i]():f.interval&&e.pause().cycle()})}var h=function(a,c){this.$element=b(a).on("keydown.bs.carousel",b.proxy(this.keydown,this));this.$indicators=this.$element.find(".carousel-indicators");this.options=c;this.paused=this.sliding=this.interval=this.$active=
this.$items=null;"hover"==this.options.pause&&this.$element.on("mouseenter.bs.carousel",b.proxy(this.pause,this)).on("mouseleave.bs.carousel",b.proxy(this.cycle,this))};h.VERSION="3.2.0";h.DEFAULTS={interval:5E3,pause:"hover",wrap:true};h.prototype.keydown=function(a){switch(a.which){case 37:this.prev();break;case 39:this.next();break;default:return}a.preventDefault()};h.prototype.cycle=function(a){return a||(this.paused=false),this.interval&&clearInterval(this.interval),this.options.interval&&!this.paused&&
(this.interval=setInterval(b.proxy(this.next,this),this.options.interval)),this};h.prototype.getItemIndex=function(a){return this.$items=a.parent().children(".item"),this.$items.index(a||this.$active)};h.prototype.to=function(a){var c=this,e=this.getItemIndex(this.$active=this.$element.find(".item.active"));return a>this.$items.length-1||0>a?void 0:this.sliding?this.$element.one("slid.bs.carousel",function(){c.to(a)}):e==a?this.pause().cycle():this.slide(a>e?"next":"prev",b(this.$items[a]))};h.prototype.pause=
function(a){return a||(this.paused=true),this.$element.find(".next, .prev").length&&b.support.transition&&(this.$element.trigger(b.support.transition.end),this.cycle(true)),this.interval=clearInterval(this.interval),this};h.prototype.next=function(){return this.sliding?void 0:this.slide("next")};h.prototype.prev=function(){return this.sliding?void 0:this.slide("prev")};h.prototype.slide=function(a,c){var e=this.$element.find(".item.active"),f=c||e[a](),i=this.interval,j="next"==a?"left":"right",k=
"next"==a?"first":"last",l=this;if(!f.length){if(!this.options.wrap)return;f=this.$element.find(".item")[k]()}if(f.hasClass("active"))return this.sliding=false;k=f[0];var m=b.Event("slide.bs.carousel",{relatedTarget:k,direction:j});if(this.$element.trigger(m),!m.isDefaultPrevented()){if(this.sliding=true,i&&this.pause(),this.$indicators.length){this.$indicators.find(".active").removeClass("active");(m=b(this.$indicators.children()[this.getItemIndex(f)]))&&m.addClass("active")}var n=b.Event("slid.bs.carousel",
{relatedTarget:k,direction:j});return b.support.transition&&this.$element.hasClass("slide")?(f.addClass(a),e.addClass(j),f.addClass(j),e.one("bsTransitionEnd",function(){f.removeClass([a,j].join(" ")).addClass("active");e.removeClass(["active",j].join(" "));l.sliding=false;setTimeout(function(){l.$element.trigger(n)},0)}).emulateTransitionEnd(1E3*e.css("transition-duration").slice(0,-1))):(e.removeClass("active"),f.addClass("active"),this.sliding=false,this.$element.trigger(n)),i&&this.cycle(),this}};
var d=b.fn.carousel;b.fn.carousel=g;b.fn.carousel.Constructor=h;b.fn.carousel.noConflict=function(){return b.fn.carousel=d,this};b(document).on("click.bs.carousel.data-api","[data-slide], [data-slide-to]",function(a){var c,e=b(this),f=b(e.attr("data-target")||(c=e.attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,""));if(f.hasClass("carousel")){c=b.extend({},f.data(),e.data());(e=e.attr("data-slide-to"))&&(c.interval=false);g.call(f,c);e&&f.data("bs.carousel").to(e);a.preventDefault()}});b(window).on("load",
function(){b('[data-ride="carousel"]').each(function(){var a=b(this);g.call(a,a.data())})})})(jQuery);
(function(b){function g(a){return this.each(function(){var c=b(this),e=c.data("bs.collapse"),f=b.extend({},h.DEFAULTS,c.data(),"object"==typeof a&&a);!e&&f.toggle&&"show"==a&&(a=!a);e||c.data("bs.collapse",e=new h(this,f));"string"==typeof a&&e[a]()})}var h=function(a,c){this.$element=b(a);this.options=b.extend({},h.DEFAULTS,c);this.transitioning=null;this.options.parent&&(this.$parent=b(this.options.parent));this.options.toggle&&this.toggle()};h.VERSION="3.2.0";h.DEFAULTS={toggle:true};h.prototype.dimension=
function(){return this.$element.hasClass("width")?"width":"height"};h.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a=b.Event("show.bs.collapse");if(this.$element.trigger(a),!a.isDefaultPrevented()){if((a=this.$parent&&this.$parent.find("> .panel > .in"))&&a.length){var c=a.data("bs.collapse");if(c&&c.transitioning)return;g.call(a,"hide");c||a.data("bs.collapse",null)}var e=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[e](0);this.transitioning=
1;a=function(){this.$element.removeClass("collapsing").addClass("collapse in")[e]("");this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);c=b.camelCase(["scroll",e].join("-"));this.$element.one("bsTransitionEnd",b.proxy(a,this)).emulateTransitionEnd(350)[e](this.$element[0][c])}}};h.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");if(this.$element.trigger(a),!a.isDefaultPrevented()){a=
this.dimension();this.$element[a](this.$element[a]());this.$element.addClass("collapsing").removeClass("collapse").removeClass("in");this.transitioning=1;var c=function(){this.transitioning=0;this.$element.trigger("hidden.bs.collapse").removeClass("collapsing").addClass("collapse")};return b.support.transition?void this.$element[a](0).one("bsTransitionEnd",b.proxy(c,this)).emulateTransitionEnd(350):c.call(this)}}};h.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};var d=
b.fn.collapse;b.fn.collapse=g;b.fn.collapse.Constructor=h;b.fn.collapse.noConflict=function(){return b.fn.collapse=d,this};b(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(a){var c,e=b(this);a=e.attr("data-target")||a.preventDefault()||(c=e.attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,"");c=b(a);var f=(a=c.data("bs.collapse"))?"toggle":e.data(),i=e.attr("data-parent"),j=i&&b(i);a&&a.transitioning||(j&&j.find('[data-toggle="collapse"][data-parent="'+i+'"]').not(e).addClass("collapsed"),
e[c.hasClass("in")?"addClass":"removeClass"]("collapsed"));g.call(c,f)})})(jQuery);
(function(b){function g(f){f&&3===f.which||(b(d).remove(),b(a).each(function(){var i=h(b(this)),j={relatedTarget:this};i.hasClass("open")&&(i.trigger(f=b.Event("hide.bs.dropdown",j)),f.isDefaultPrevented()||i.removeClass("open").trigger("hidden.bs.dropdown",j))}))}function h(f){var i=f.attr("data-target");i||(i=f.attr("href"),i=i&&/#[A-Za-z]/.test(i)&&i.replace(/.*(?=#[^\s]*$)/,""));return(i=i&&b(i))&&i.length?i:f.parent()}var d=".dropdown-backdrop",a='[data-toggle="dropdown"]',c=function(f){b(f).on("click.bs.dropdown",
this.toggle)};c.VERSION="3.2.0";c.prototype.toggle=function(f){var i=b(this);if(!i.is(".disabled, :disabled")){var j=h(i),k=j.hasClass("open");if(g(),!k){"ontouchstart"in document.documentElement&&!j.closest(".navbar-nav").length&&b('<div class="dropdown-backdrop"/>').insertAfter(b(this)).on("click",g);k={relatedTarget:this};if(j.trigger(f=b.Event("show.bs.dropdown",k)),f.isDefaultPrevented())return;i.trigger("focus");j.toggleClass("open").trigger("shown.bs.dropdown",k)}return false}};c.prototype.keydown=
function(f){if(/(38|40|27)/.test(f.keyCode)){var i=b(this);if(f.preventDefault(),f.stopPropagation(),!i.is(".disabled, :disabled")){var j=h(i),k=j.hasClass("open");if(!k||k&&27==f.keyCode)return 27==f.which&&j.find(a).trigger("focus"),i.trigger("click");i=j.find('[role="menu"] li:not(.divider):visible a, [role="listbox"] li:not(.divider):visible a');if(i.length){j=i.index(i.filter(":focus"));38==f.keyCode&&j>0&&j--;40==f.keyCode&&j<i.length-1&&j++;~j||(j=0);i.eq(j).trigger("focus")}}}};var e=b.fn.dropdown;
b.fn.dropdown=function(f){return this.each(function(){var i=b(this),j=i.data("bs.dropdown");j||i.data("bs.dropdown",j=new c(this));"string"==typeof f&&j[f].call(i)})};b.fn.dropdown.Constructor=c;b.fn.dropdown.noConflict=function(){return b.fn.dropdown=e,this};b(document).on("click.bs.dropdown.data-api",g).on("click.bs.dropdown.data-api",".dropdown form",function(f){f.stopPropagation()}).on("click.bs.dropdown.data-api",a,c.prototype.toggle).on("keydown.bs.dropdown.data-api",a+', [role="menu"], [role="listbox"]',
c.prototype.keydown)})(jQuery);
(function(b){function g(a,c){return this.each(function(){var e=b(this),f=e.data("bs.modal"),i=b.extend({},h.DEFAULTS,e.data(),"object"==typeof a&&a);f||e.data("bs.modal",f=new h(this,i));"string"==typeof a?f[a](c):i.show&&f.show(c)})}var h=function(a,c){this.options=c;this.$body=b(document.body);this.$element=b(a);this.$backdrop=this.isShown=null;this.scrollbarWidth=0;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,b.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};
h.VERSION="3.2.0";h.DEFAULTS={backdrop:true,keyboard:true,show:true};h.prototype.toggle=function(a){return this.isShown?this.hide():this.show(a)};h.prototype.show=function(a){var c=this,e=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(e);this.isShown||e.isDefaultPrevented()||(this.isShown=true,this.checkScrollbar(),this.$body.addClass("modal-open"),this.setScrollbar(),this.escape(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',b.proxy(this.hide,this)),this.backdrop(function(){var f=
b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(c.$body);c.$element.show().scrollTop(0);c.$element.addClass("in").attr("aria-hidden",false);c.enforceFocus();var i=b.Event("shown.bs.modal",{relatedTarget:a});f?c.$element.find(".modal-dialog").one("bsTransitionEnd",function(){c.$element.trigger("focus").trigger(i)}).emulateTransitionEnd(300):c.$element.trigger("focus").trigger(i)}))};h.prototype.hide=function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");
this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=false,this.$body.removeClass("modal-open"),this.resetScrollbar(),this.escape(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",true).off("click.dismiss.bs.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one("bsTransitionEnd",b.proxy(this.hideModal,this)).emulateTransitionEnd(300):this.hideModal())};h.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",
b.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.trigger("focus")},this))};h.prototype.escape=function(){this.isShown&&this.options.keyboard?this.$element.on("keyup.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this)):this.isShown||this.$element.off("keyup.dismiss.bs.modal")};h.prototype.hideModal=function(){var a=this;this.$element.hide();this.backdrop(function(){a.$element.trigger("hidden.bs.modal")})};h.prototype.removeBackdrop=
function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};h.prototype.backdrop=function(a){var c=this,e=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var f=b.support.transition&&e;if(!(this.$backdrop=b('<div class="modal-backdrop '+e+'" />').appendTo(this.$body),this.$element.on("click.dismiss.bs.modal",b.proxy(function(i){i.target===i.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus.call(this.$element[0]):this.hide.call(this))},
this)),this.$backdrop.addClass("in"),!a))f?this.$backdrop.one("bsTransitionEnd",a).emulateTransitionEnd(150):a()}else if(!this.isShown&&this.$backdrop){this.$backdrop.removeClass("in");e=function(){c.removeBackdrop();a&&a()};b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one("bsTransitionEnd",e).emulateTransitionEnd(150):e()}else a&&a()};h.prototype.checkScrollbar=function(){document.body.clientWidth>=window.innerWidth||(this.scrollbarWidth=this.scrollbarWidth||this.measureScrollbar())};
h.prototype.setScrollbar=function(){var a=parseInt(this.$body.css("padding-right")||0,10);this.scrollbarWidth&&this.$body.css("padding-right",a+this.scrollbarWidth)};h.prototype.resetScrollbar=function(){this.$body.css("padding-right","")};h.prototype.measureScrollbar=function(){var a=document.createElement("div");a.className="modal-scrollbar-measure";this.$body.append(a);var c=a.offsetWidth-a.clientWidth;return this.$body[0].removeChild(a),c};var d=b.fn.modal;b.fn.modal=g;b.fn.modal.Constructor=
h;b.fn.modal.noConflict=function(){return b.fn.modal=d,this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),e=c.attr("href"),f=b(c.attr("data-target")||e&&e.replace(/.*(?=#[^\s]+$)/,""));e=f.data("bs.modal")?"toggle":b.extend({remote:!/#/.test(e)&&e},f.data(),c.data());c.is("a")&&a.preventDefault();f.one("show.bs.modal",function(i){i.isDefaultPrevented()||f.one("hidden.bs.modal",function(){c.is(":visible")&&c.trigger("focus")})});g.call(f,e,this)})})(jQuery);
(function(b){var g=function(d,a){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",d,a)};g.VERSION="3.2.0";g.DEFAULTS={animation:true,placement:"top",selector:false,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:false,container:false,viewport:{selector:"body",padding:0}};g.prototype.init=function(d,a,c){this.enabled=true;this.type=
d;this.$element=b(a);this.options=this.getOptions(c);this.$viewport=this.options.viewport&&b(this.options.viewport.selector||this.options.viewport);d=this.options.trigger.split(" ");for(a=d.length;a--;){c=d[a];if("click"==c)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else if("manual"!=c){var e="hover"==c?"mouseleave":"focusout";this.$element.on(("hover"==c?"mouseenter":"focusin")+"."+this.type,this.options.selector,b.proxy(this.enter,this));this.$element.on(e+
"."+this.type,this.options.selector,b.proxy(this.leave,this))}}this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};g.prototype.getDefaults=function(){return g.DEFAULTS};g.prototype.getOptions=function(d){return d=b.extend({},this.getDefaults(),this.$element.data(),d),d.delay&&"number"==typeof d.delay&&(d.delay={show:d.delay,hide:d.delay}),d};g.prototype.getDelegateOptions=function(){var d={},a=this.getDefaults();return this._options&&b.each(this._options,
function(c,e){a[c]!=e&&(d[c]=e)}),d};g.prototype.enter=function(d){var a=d instanceof this.constructor?d:b(d.currentTarget).data("bs."+this.type);return a||(a=new this.constructor(d.currentTarget,this.getDelegateOptions()),b(d.currentTarget).data("bs."+this.type,a)),clearTimeout(a.timeout),a.hoverState="in",a.options.delay&&a.options.delay.show?void(a.timeout=setTimeout(function(){"in"==a.hoverState&&a.show()},a.options.delay.show)):a.show()};g.prototype.leave=function(d){var a=d instanceof this.constructor?
d:b(d.currentTarget).data("bs."+this.type);return a||(a=new this.constructor(d.currentTarget,this.getDelegateOptions()),b(d.currentTarget).data("bs."+this.type,a)),clearTimeout(a.timeout),a.hoverState="out",a.options.delay&&a.options.delay.hide?void(a.timeout=setTimeout(function(){"out"==a.hoverState&&a.hide()},a.options.delay.hide)):a.hide()};g.prototype.show=function(){var d=b.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled){this.$element.trigger(d);var a=b.contains(document.documentElement,
this.$element[0]);if(!(d.isDefaultPrevented()||!a)){var c=this;d=this.tip();a=this.getUID(this.type);this.setContent();d.attr("id",a);this.$element.attr("aria-describedby",a);this.options.animation&&d.addClass("fade");a="function"==typeof this.options.placement?this.options.placement.call(this,d[0],this.$element[0]):this.options.placement;var e=/\s?auto?\s?/i,f=e.test(a);f&&(a=a.replace(e,"")||"top");d.detach().css({top:0,left:0,display:"block"}).addClass(a).data("bs."+this.type,this);this.options.container?
d.appendTo(this.options.container):d.insertAfter(this.$element);e=this.getPosition();var i=d[0].offsetWidth,j=d[0].offsetHeight;if(f){f=a;var k=this.getPosition(this.$element.parent());a="bottom"==a&&e.top+e.height+j-k.scroll>k.height?"top":"top"==a&&e.top-k.scroll-j<0?"bottom":"right"==a&&e.right+i>k.width?"left":"left"==a&&e.left-i<k.left?"right":a;d.removeClass(f).addClass(a)}this.applyPlacement(this.getCalculatedOffset(a,e,i,j),a);a=function(){c.$element.trigger("shown.bs."+c.type);c.hoverState=
null};b.support.transition&&this.$tip.hasClass("fade")?d.one("bsTransitionEnd",a).emulateTransitionEnd(150):a()}}};g.prototype.applyPlacement=function(d,a){var c=this.tip(),e=c[0].offsetWidth,f=c[0].offsetHeight,i=parseInt(c.css("margin-top"),10),j=parseInt(c.css("margin-left"),10);isNaN(i)&&(i=0);isNaN(j)&&(j=0);d.top+=i;d.left+=j;b.offset.setOffset(c[0],b.extend({using:function(l){c.css({top:Math.round(l.top),left:Math.round(l.left)})}},d),0);c.addClass("in");j=c[0].offsetWidth;var k=c[0].offsetHeight;
"top"==a&&k!=f&&(d.top=d.top+f-k);i=this.getViewportAdjustedDelta(a,d,j,k);i.left?d.left+=i.left:d.top+=i.top;e=i.left?2*i.left-e+j:2*i.top-f+k;f=i.left?"left":"top";i=i.left?"offsetWidth":"offsetHeight";c.offset(d);this.replaceArrow(e,c[0][i],f)};g.prototype.replaceArrow=function(d,a,c){this.arrow().css(c,d?50*(1-d/a)+"%":"")};g.prototype.setContent=function(){var d=this.tip(),a=this.getTitle();d.find(".tooltip-inner")[this.options.html?"html":"text"](a);d.removeClass("fade in top bottom left right")};
g.prototype.hide=function(){function d(){"in"!=a.hoverState&&c.detach();a.$element.trigger("hidden.bs."+a.type)}var a=this,c=this.tip(),e=b.Event("hide.bs."+this.type);return this.$element.removeAttr("aria-describedby"),this.$element.trigger(e),e.isDefaultPrevented()?void 0:(c.removeClass("in"),b.support.transition&&this.$tip.hasClass("fade")?c.one("bsTransitionEnd",d).emulateTransitionEnd(150):d(),this.hoverState=null,this)};g.prototype.fixTitle=function(){var d=this.$element;(d.attr("title")||"string"!=
typeof d.attr("data-original-title"))&&d.attr("data-original-title",d.attr("title")||"").attr("title","")};g.prototype.hasContent=function(){return this.getTitle()};g.prototype.getPosition=function(d){d=d||this.$element;var a=d[0],c="BODY"==a.tagName;return b.extend({},"function"==typeof a.getBoundingClientRect?a.getBoundingClientRect():null,{scroll:c?document.documentElement.scrollTop||document.body.scrollTop:d.scrollTop(),width:c?b(window).width():d.outerWidth(),height:c?b(window).height():d.outerHeight()},
c?{top:0,left:0}:d.offset())};g.prototype.getCalculatedOffset=function(d,a,c,e){return"bottom"==d?{top:a.top+a.height,left:a.left+a.width/2-c/2}:"top"==d?{top:a.top-e,left:a.left+a.width/2-c/2}:"left"==d?{top:a.top+a.height/2-e/2,left:a.left-c}:{top:a.top+a.height/2-e/2,left:a.left+a.width}};g.prototype.getViewportAdjustedDelta=function(d,a,c,e){var f={top:0,left:0};if(!this.$viewport)return f;var i=this.options.viewport&&this.options.viewport.padding||0,j=this.getPosition(this.$viewport);if(/right|left/.test(d)){c=
a.top-i-j.scroll;a=a.top+i-j.scroll+e;c<j.top?f.top=j.top-c:a>j.top+j.height&&(f.top=j.top+j.height-a)}else{e=a.left-i;a=a.left+i+c;e<j.left?f.left=j.left-e:a>j.width&&(f.left=j.left+j.width-a)}return f};g.prototype.getTitle=function(){var d=this.$element,a=this.options;return d.attr("data-original-title")||("function"==typeof a.title?a.title.call(d[0]):a.title)};g.prototype.getUID=function(d){do d+=~~(1E6*Math.random());while(document.getElementById(d));return d};g.prototype.tip=function(){return this.$tip=
this.$tip||b(this.options.template)};g.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};g.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.$element=null,this.options=null)};g.prototype.enable=function(){this.enabled=true};g.prototype.disable=function(){this.enabled=false};g.prototype.toggleEnabled=function(){this.enabled=!this.enabled};g.prototype.toggle=function(d){var a=this;d&&(a=b(d.currentTarget).data("bs."+this.type),a||
(a=new this.constructor(d.currentTarget,this.getDelegateOptions()),b(d.currentTarget).data("bs."+this.type,a)));a.tip().hasClass("in")?a.leave(a):a.enter(a)};g.prototype.destroy=function(){clearTimeout(this.timeout);this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var h=b.fn.tooltip;b.fn.tooltip=function(d){return this.each(function(){var a=b(this),c=a.data("bs.tooltip"),e="object"==typeof d&&d;(c||"destroy"!=d)&&(c||a.data("bs.tooltip",c=new g(this,e)),"string"==typeof d&&c[d]())})};
b.fn.tooltip.Constructor=g;b.fn.tooltip.noConflict=function(){return b.fn.tooltip=h,this}})(jQuery);
(function(b){var g=function(d,a){this.init("popover",d,a)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");g.VERSION="3.2.0";g.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});g.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);g.prototype.constructor=g;g.prototype.getDefaults=function(){return g.DEFAULTS};
g.prototype.setContent=function(){var d=this.tip(),a=this.getTitle(),c=this.getContent();d.find(".popover-title")[this.options.html?"html":"text"](a);d.find(".popover-content").empty()[this.options.html?"string"==typeof c?"html":"append":"text"](c);d.removeClass("fade top bottom left right in");d.find(".popover-title").html()||d.find(".popover-title").hide()};g.prototype.hasContent=function(){return this.getTitle()||this.getContent()};g.prototype.getContent=function(){var d=this.$element,a=this.options;
return d.attr("data-content")||("function"==typeof a.content?a.content.call(d[0]):a.content)};g.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};g.prototype.tip=function(){return this.$tip||(this.$tip=b(this.options.template)),this.$tip};var h=b.fn.popover;b.fn.popover=function(d){return this.each(function(){var a=b(this),c=a.data("bs.popover"),e="object"==typeof d&&d;(c||"destroy"!=d)&&(c||a.data("bs.popover",c=new g(this,e)),"string"==typeof d&&c[d]())})};b.fn.popover.Constructor=
g;b.fn.popover.noConflict=function(){return b.fn.popover=h,this}})(jQuery);
(function(b){function g(a,c){var e=b.proxy(this.process,this);this.$body=b("body");this.$scrollElement=b(b(a).is("body")?window:a);this.options=b.extend({},g.DEFAULTS,c);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",e);this.refresh();this.process()}function h(a){return this.each(function(){var c=b(this),e=c.data("bs.scrollspy"),f="object"==typeof a&&a;e||c.data("bs.scrollspy",
e=new g(this,f));"string"==typeof a&&e[a]()})}g.VERSION="3.2.0";g.DEFAULTS={offset:10};g.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};g.prototype.refresh=function(){var a="offset",c=0;b.isWindow(this.$scrollElement[0])||(a="position",c=this.$scrollElement.scrollTop());this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();var e=this;this.$body.find(this.selector).map(function(){var f=
b(this);f=f.data("target")||f.attr("href");var i=/^#./.test(f)&&b(f);return i&&i.length&&i.is(":visible")&&[[i[a]().top+c,f]]||null}).sort(function(f,i){return f[0]-i[0]}).each(function(){e.offsets.push(this[0]);e.targets.push(this[1])})};g.prototype.process=function(){var a,c=this.$scrollElement.scrollTop()+this.options.offset,e=this.getScrollHeight(),f=this.options.offset+e-this.$scrollElement.height(),i=this.offsets,j=this.targets,k=this.activeTarget;if(this.scrollHeight!=e&&this.refresh(),c>=
f)return k!=(a=j[j.length-1])&&this.activate(a);if(k&&c<=i[0])return k!=(a=j[0])&&this.activate(a);for(a=i.length;a--;)k!=j[a]&&c>=i[a]&&(!i[a+1]||c<=i[a+1])&&this.activate(j[a])};g.prototype.activate=function(a){this.activeTarget=a;b(this.selector).parentsUntil(this.options.target,".active").removeClass("active");a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));
a.trigger("activate.bs.scrollspy")};var d=b.fn.scrollspy;b.fn.scrollspy=h;b.fn.scrollspy.Constructor=g;b.fn.scrollspy.noConflict=function(){return b.fn.scrollspy=d,this};b(window).on("load.bs.scrollspy.data-api",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);h.call(a,a.data())})})})(jQuery);
(function(b){function g(a){return this.each(function(){var c=b(this),e=c.data("bs.tab");e||c.data("bs.tab",e=new h(this));"string"==typeof a&&e[a]()})}var h=function(a){this.element=b(a)};h.VERSION="3.2.0";h.prototype.show=function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),e=a.data("target");if(e||(e=a.attr("href"),e=e&&e.replace(/.*(?=#[^\s]*$)/,"")),!a.parent("li").hasClass("active")){var f=c.find(".active:last a")[0],i=b.Event("show.bs.tab",{relatedTarget:f});if(a.trigger(i),!i.isDefaultPrevented()){e=
b(e);this.activate(a.closest("li"),c);this.activate(e,e.parent(),function(){a.trigger({type:"shown.bs.tab",relatedTarget:f})})}}};h.prototype.activate=function(a,c,e){function f(){i.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");j?a.addClass("in"):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");e&&e()}var i=c.find("> .active"),j=e&&b.support.transition&&i.hasClass("fade");j?i.one("bsTransitionEnd",f).emulateTransitionEnd(150):
f();i.removeClass("in")};var d=b.fn.tab;b.fn.tab=g;b.fn.tab.Constructor=h;b.fn.tab.noConflict=function(){return b.fn.tab=d,this};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();g.call(b(this),"show")})})(jQuery);
(function(b){function g(a){return this.each(function(){var c=b(this),e=c.data("bs.affix"),f="object"==typeof a&&a;e||c.data("bs.affix",e=new h(this,f));"string"==typeof a&&e[a]()})}var h=function(a,c){this.options=b.extend({},h.DEFAULTS,c);this.$target=b(this.options.target).on("scroll.bs.affix.data-api",b.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",b.proxy(this.checkPositionWithEventLoop,this));this.$element=b(a);this.affixed=this.unpin=this.pinnedOffset=null;this.checkPosition()};
h.VERSION="3.2.0";h.RESET="affix affix-top affix-bottom";h.DEFAULTS={offset:0,target:window};h.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(h.RESET).addClass("affix");var a=this.$target.scrollTop();return this.pinnedOffset=this.$element.offset().top-a};h.prototype.checkPositionWithEventLoop=function(){setTimeout(b.proxy(this.checkPosition,this),1)};h.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=b(document).height(),
c=this.$target.scrollTop(),e=this.$element.offset(),f=this.options.offset,i=f.top,j=f.bottom;"object"!=typeof f&&(j=i=f);"function"==typeof i&&(i=f.top(this.$element));"function"==typeof j&&(j=f.bottom(this.$element));c=null!=this.unpin&&c+this.unpin<=e.top?false:null!=j&&e.top+this.$element.height()>=a-j?"bottom":null!=i&&i>=c?"top":false;if(this.affixed!==c){null!=this.unpin&&this.$element.css("top","");e="affix"+(c?"-"+c:"");f=b.Event(e+".bs.affix");this.$element.trigger(f);f.isDefaultPrevented()||
(this.affixed=c,this.unpin="bottom"==c?this.getPinnedOffset():null,this.$element.removeClass(h.RESET).addClass(e).trigger(b.Event(e.replace("affix","affixed"))),"bottom"==c&&this.$element.offset({top:a-this.$element.height()-j}))}}};var d=b.fn.affix;b.fn.affix=g;b.fn.affix.Constructor=h;b.fn.affix.noConflict=function(){return b.fn.affix=d,this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};c.offsetBottom&&(c.offset.bottom=c.offsetBottom);
c.offsetTop&&(c.offset.top=c.offsetTop);g.call(a,c)})})})(jQuery);var FB_Share=0,FB_Like=1,FB_Like_But_No_Share=2,FB_Embed=3,FB_Comment=4,FB_LikeBox=5,Twitter_Share=6;
$(document).ready(function(){if(location.href.indexOf("localhost")==-1){(function(b,g,h){var d=b.getElementsByTagName(g)[0];if(!b.getElementById(h)){b=b.createElement(g);b.id=h;b.src="//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=720631857995720&version=v2.0";d.parentNode.insertBefore(b,d)}})(document,"script","facebook-jssdk");(function(b,g,h,d,a,c,e){b.GoogleAnalyticsObject=a;b[a]=b[a]||function(){(b[a].q=b[a].q||[]).push(arguments)};b[a].l=1*new Date;c=g.createElement(h);e=g.getElementsByTagName(h)[0];
c.async=1;c.src=d;e.parentNode.insertBefore(c,e)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-50069779-1","infonexus.in");ga("send","pageview")}});
function Build_Social_Button(b,g,h){h=h==undefined?100:h;var d="";switch(b){case FB_Share:d="<div class='fb-share-button' data-href='"+g+"' data-width='"+h+"'></div>";break;case FB_Like:d="<div class='fb-like' data-href='"+g+"' data-width='"+h+"' data-layout='button' data-action='like' data-show-faces='true' data-share='true'></div>";break;case FB_Like_But_No_Share:d="<div class='fb-like' data-href='"+g+"' data-width='"+h+"' data-layout='button' data-action='like' data-show-faces='true' data-share='false'></div>";
break;case FB_Embed:d="<div class='fb-post' data-href='"+g+"' data-width='"+h+"'></div>";break;case FB_Comment:d="<div class='fb-comments' data-href='"+g+"' data-numposts='5' data-colorscheme='light'></div>";break;case FB_LikeBox:d="<div class='fb-like-box' data-href='"+g+"' data-colorscheme='light' data-show-faces='true' data-header='true' data-stream='false' data-show-border='true'></div>";break;case Twitter_Share:d="<a href='https://twitter.com/share' class='twitter-share-button'>Tweet</a>"}return d}
function GetErrorMessage(b){return"<span class='text-danger'>"+b+"<span>"}function GetSuccessMessage(b){return"<span class='text-success'>"+b+"<span>"}var Ad_Amazon_LeaderBoad=0,Ad_Amazon_Square=1,Ad_Chitika=2;
function CreateAdBlocks(b,g,h){var d="";switch(b){case Ad_Amazon_LeaderBoad:d="<div class='alignleft'><script type='text/javascript'>amzn_assoc_ad_type = 'banner';amzn_assoc_tracking_id = 'infonexus-20';amzn_assoc_marketplace = 'amazon';amzn_assoc_region = 'US';amzn_assoc_placement = 'assoc_banner_placement_default';amzn_assoc_linkid = 'X4F2RHGBBMKNM5C4';amzn_assoc_campaigns = 'electronicsrot';amzn_assoc_p = '48';amzn_assoc_banner_type = 'rotating';amzn_assoc_width = '"+g+"';amzn_assoc_height = '90';<\/script><script src='//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1'><\/script></div>";
break;case Ad_Amazon_Square:d="<div class='alignleft'><script type='text/javascript'>amzn_assoc_ad_type = 'banner';amzn_assoc_tracking_id = 'infonexus-20';amzn_assoc_marketplace = 'amazon';amzn_assoc_region = 'US';amzn_assoc_placement = 'assoc_banner_placement_default';amzn_assoc_linkid = 'HKELMAKQQ6OVEER5';amzn_assoc_campaigns = 'electronicsrot';amzn_assoc_p = '12';amzn_assoc_banner_type = 'rotating';amzn_assoc_width = '"+g+"';amzn_assoc_height = '"+g+"';<\/script><script src='//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1'><\/script></div>";
break;case Ad_Chitika:d="<script type='text/javascript'>( function() {if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };var unit = {'calltype':'async[2]','publisher':'infonexus','width':"+g+",'height':"+h+",'sid':'Chitika Default'};var placement_id = window.CHITIKA.units.length;window.CHITIKA.units.push(unit);document.write('<div id='chitikaAdBlock-' + placement_id + ''></div>');}());<\/script><script type='text/javascript' src='//cdn.chitika.net/getads.js' async><\/script>"}return d}
function ShowMessagorForMobileSite(){if(window.localStorage.getItem("_lma")==null){$("#mymodal").modal("show");$("#modalTitle").html("View Mobile version");$("#modalBody").html("<span style='font-weight: bold;color: rgb(114, 119, 210);'>Mobile version of website is also available.</span><br/> <br/><a href='http://infonexus.in/mobile' class='btn btn-block btn-info'>Goto Mobile View</a>");$("#btnmodalclose").text("No thanks, Continue with Desktop Version");window.localStorage.setItem("_lma","1")}}var currentlang;
$(window).resize(Resize);$(document).ready(function(){Resize();var b=$(window).width();b>500&&currentlang==""?CreatIndex():$("#divindex").hide();b<500&&ShowMessagorForMobileSite();$(".btnSearch").bind("click",search);$("#txtSearch").keypress(function(g){g.keyCode==13&&search()})});function search(){var b=$("#txtSearch").val().trim();if(b=="")return false;location.href="/learningzone/searchpage.aspx?q="+b}
function Resize(){if($(window).width()>500){if(currentlang==""&&$("#wordcloud").html()!=undefined){$("#wordcloud").html("");$("#wordcloud").jQCloud(word_list);$("#wordcloud").css({width:"100%"})}$("#divindex").show()}else $("#divindex").hide();var b=$(window).height()-47;$(".contentdiv").css({"min-height":b-($(".top").height()+$(".foot").height()+$(".foot1").height())})}
$(window).scroll(function(){var b=$(this).scrollTop();if(b>150){$(".imglogo, .tdsep").css({height:40,"margin-top":10});$("#swtop").hide();$(".top").removeClass("fixedTop").addClass("NofixedTop");$(".top").height(69)}else{$(".imglogo, .tdsep").css({height:60,"margin-top":11});$("#swtop").show();$(".top").removeClass("NofixedTop").addClass("fixedTop");$(".top").height(85)}b<=50?$(".gotop").hide():$(".gotop").show()});
function Showprocessing(){$("#divProcessingMessage").html("<img src='/Images/processing1.gif' style='height:23px;' /><br />Processing, please wait...");$("#divProcessingMessage").show();$("#divProcessingMessage").css({left:$(window).width()/2-$("#divProcessingMessage").width()/2})}function Hideprocessing(){$("#divProcessingMessage").html("");$("#divProcessingMessage").hide()}var queslist;
$(window).bind("load",function(){queslist==true&&$(".spnhome").show();$("#fbShare").html(Build_Social_Button(FB_Like,location.href));$("#twitter").html(Build_Social_Button(Twitter_Share,location.href))});function GoTop(){$("body").animate({scrollTop:0},"slow")}var induction=[];induction[0]={color:"#808080",title:"Interview Questions",text:"Find interview questions of C#.NET, ASP.NET, Database, JQuery, JavaScript, Google Map and various other technologies."};
induction[1]={color:"#f2dede",title:"Tutorials",text:"Find tutorials having long, short and multiple choice questions. Play puzzle with multiple choice questions."};induction[2]={color:"#209B2A",title:"Code Samples",text:"Find code samples of various technologies. Learn interesting facts by doing practical of code samples."};induction[3]={color:"#a94442",title:"Competitive Preparation",text:"Find learning materials of Current Affairs, Geography, History and various other subjects."};
function CreatIndex(){var b=["<div class='container'><div class='row'><div class='col-md-6 col-sm-6 col-xs-12 visible-lg visible-md visible-sm'>"];b[b.length]="<div id='wordcloud' class='jqcloud'></div></div>";b[b.length]="<div class='col-md-6 col-sm-6 col-xs-12 visible-lg visible-md visible-sm'><div class='dtext'><div class='dtitle'>Interview Questions</div><div class='d2'>"+induction[0].text+"</div></div></div></div></div>";$("#divindex").html(b.join(""));$("#divindex .d1").on("click, mouseover",
function(){g=$(this).data("i");showtxt(g)});$("#wordcloud").jQCloud(word_list);var g=0;window.setInterval(function(){if(g==induction.length)g=0;showtxt(g++)},3E3)}function showtxt(b){$(".d2").text(induction[b].text);$(".dtitle").text(induction[b].title)}
function SendFeedback(){var b=$("#txtFeedBackUserName").val(),g=$("#txtFeedBackEmail").val(),h=$("#txtFeedback").val(),d="";if(b=="")d="Your good name is missing.";if(g=="")d="Email id missing";else if(g.indexOf("@")==-1||g.indexOf(".")==-1)d="Please enter valid email id.";if(h=="")d="Please enter your valuable feedback.";if(d!=""){$("#lblMsg").html("<span class='text-error'>"+d+"</span>");return false}$.post("/learningzone/query.aspx?Action=SF",{username:b,email:g,feedback:h},function(){});$("#lblMsg").html("<span style='margin-left:10px; color:white;'>Thank you very much for your feedback.</span>");
window.setTimeout(function(){$("#txtFeedBackUserName").val("");$("#txtFeedBackEmail").val("");$("#txtFeedback").val("");$("#lblMsg").html("")},3E3);return false}
var word_list=[{text:"C#",weight:6,link:"/c-sharp-subjective"},{text:"Current Affairs",weight:3.5,link:"/exam-preparation-current-affairs-hindi"},{text:"ASP.NET",weight:3.5,link:"/aspnet-subjective"},{text:"HTML",weight:2},{text:"Code Samples",weight:2},{text:"History",weight:3,link:"competitive-preparation-hindi-history"},{text:"Joins",weight:2},{text:"Grant",weight:2},{text:"LINQ",weight:2},{text:"Warehousing",weight:2},{text:"Database",weight:3,link:"/database-subjective"},{text:"JQuery",weight:2},
{text:"JQuery-Mobile",weight:2},{text:"Google Map",weight:3,link:"/programming-language-google-map"},{text:"Primary Key",weight:3,link:"/database-objective"},{text:"Aptitude",weight:3,link:"/exam-preparation-aptitude-and-reasoning"},{text:"Reasoning",weight:2.5,link:"/exam-preparation-aptitude-and-reasoning"},{text:"Geography",weight:3,link:"/competitive-preparation-english-geography"},{text:"General Knowledge",weight:3,link:"/competitive-preparation-english-general-knowledge"},{text:"Managed Code",
weight:2},{text:"Reflection",weight:2},{text:"Session",weight:2},{text:"Postback",weight:2},{text:"Bubbled Events",weight:2},{text:"User Controls",weight:2},{text:"Impersonation",weight:2}];
