$.fn.serializeObject=function(){var a={};$("input,select,checkbox,password,radio,textarea,input:hidden",this).each(function(){var b=$(this).attr("id"),c=$.trim($(this).val());if(this.type=="checkbox"||this.type=="radio")this.checked||(c="0");a[b]=c});return a};function htmlEncode(a){return $("<div/>").text(a).html()}function htmlDecode(a){return $("<div/>").html(a).text()}
function ShowWait(){var a="<br><table cellpadding='0' cellspacing='0' width='100%' >";a+="<tr><td>&nbsp;<tr><td colspan='4' align='center'><img src='Images/progress.gif' alt='progress'>";a+="<tr align='center'><td colspan='4' ><b>Processing request, please wait......";a+="</table>";$("#divWait").html(a);$("#divWait").dialog("open");$("#divWait").dialog("option",{title:"Processing...",position:"center"})}function EndWait(){$("#divWait").dialog("close")}
function SaveInLocalStorage(a,b){if(typeof localStorage!="undefined"){window.localStorage.removeItem("'"+a+"'");window.localStorage.setItem("'"+a+"'",b);return true}else{alert("Your browser does not support local storage, please upgrade to latest browser");return false}}function LoadFromLocalStorage(a,b){var c=window.localStorage.getItem("'"+a+"'");if(c==null)return b==undefined?"":b;return c}function RemoveFromLocalStorage(a){window.localStorage.removeItem("'"+a+"'")}
function ClearLocalStoreage(){if(typeof window.localStorage!="undefined")window.localStorage.clear();else throw"window.localStorage, not defined";}function CheckCacheUpdate(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()})}String.prototype.toProperCase=function(){return this.replace(/\w\S*/g,function(a){return a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()})};
function AddWhatsAppContent(){if(!($(window).width()>500))if($("#ques_type").text()=="0")$(".divData table.tblQuesList").each(function(){$("#wa_"+$(".answerbox",$(this)).data("id")).html("<a class='btn btn-xs' href='whatsapp://send?text="+$(".ques",$(this)).text()+"\n\n Answer : "+$(".answerbox",$(this)).text()+" \n\n, Sent from - "+location.href+"'><img src='/images/wa.jpg' /></a></span>")});else{var a=[""];$(".divData table.tblQuesList").each(function(){a=[""];$(".ulans li",$(this)).each(function(b){a[a.length]=
"\n("+(b+1)+") "+$(this).text()});$("#wa_"+$(".answerbox",$(this)).data("id")).html("<a class='btn btn-xs' href='whatsapp://send?text="+$(".ques",$(this)).text()+"\n\n Options : "+a.join("")+"\n\n Answer : "+$(".objans",$(this)).text()+", Sent from - "+location.href+"'><img src='/images/wa.jpg' /></a></span>")})}}$(window).bind("load",function(){queslist==true&&AddWhatsAppContent()});$(document).ready(function(){$(".tt").tooltip();$("#btnSendEmail").hide();ShowFav();AddClientOptions()});
function GetPlainText(a){var b=["<table style='width:100%;text-align:justify;'>"];a=="All"?$(".divData table.tblQuesList").each(function(){b[b.length]="<tr><td><b>Ques : </b>"+$(".ques",$(this)).text()+"<br/>"+($("#ques_type").text()=="0"?"":"<b>Answer : </b>")+$(".answerbox",$(this)).html()+"</b><br/><br/></td></tr>"}):$(FavList).each(function(){b[b.length]="<tr><td><b>Ques : </b>"+this.Ques+"<br/>"+(this.t==0?"":"<b>Answer : </b>")+this.Ans+"</b><br/><br/></td></tr>"});a=window.open("","_blank",
"toolbar=0,menubar=0,location=1,status=1,scrollbars=1,resizable=1,left=0,top=0");a.document.open();a.document.write('<html><body">'+b.join("")+"</html>");a.document.close()}var FavList=[];function AddToFavorite(a){if(FoundIndexInFav(a)==-1)FavList[FavList.length]={ID:a,Ques:$("#que_"+a).text(),Ans:$("#ans_"+a).html(),Type:$("#ques_type").text()};SaveFavList()}function SaveFavList(){SaveInLocalStorage("Favs",JSON.stringify(FavList));ShowFav()}
function FoundIndexInFav(a){for(var b=0;b<FavList.length;b++)if(FavList[b].ID==a)return b;return-1}
function ShowFav(){FavList=JSON.parse(LoadFromLocalStorage("Favs","[]"));$("#spnFav").text(FavList.length);$("#HCnt").show();$("#liFav").show();$("#divFavorite").hide();if(FavList.length==0){AddClientOptions();GoTop()}else{var a=["<table class='table table-condensed table-bordered table-hover' style='margin-bottom:0px'><tr><th>#<th>Question<th>Del"];$(FavList).each(function(b){a[a.length]="<tr><td>"+(b+1)+"<td><a href='#' title='Click to show or hide answer' class='ashow' data-index='"+b+"' >"+this.Ques+
"</a><span id='fav_"+b+"' style='display:none'></span><td><a href='#' class='abtn' onclick='return RemoveFromFav("+b+")'>X</a>"});a[a.length]="</table>";$("#divFavs").html(a.join(""));$("#divFavorite").show();AddClientOptions();$("#divFavorite a.ashow").bind("click",function(){var b=$(this).data("index");$("#fav_"+b).html("<br/><b>Ans : </b>"+FavList[b].Ans);$("#fav_"+b).toggle();return false})}}function RemoveFromFav(a){a==-1?FavList.length=0:FavList.splice(a,1);SaveFavList();return false}
function AddClientOptions(){$(".answerbox",$(".divData")).each(function(){var a=$(this).data("id");favindex=FoundIndexInFav(a);favindex==-1?$("#divopt_"+a).html("<div class='optbtn' title='Add to Favorite' onclick='AddToFavorite("+a+")' >&nbsp;Add&nbsp; </div>"):$("#divopt_"+a).html("<div class='optbtn rem' title='Remove from Favorite' onclick='RemoveFromFav("+favindex+")' title='Remove from Favorites'>&nbsp;Remove&nbsp;</div>")})}function GoBack(){window.history.go(-1);return false}
function ViewFavorite(){$("body").animate({scrollTop:$("#divFavs").position().top},"slow")};
