function SaveInLocalStorage(a,b){if(typeof localStorage!="undefined"){var c={dt:(new Date).getDate(),res:b};window.localStorage.setItem("'"+a+"'",JSON.stringify(c));return true}else{alert("Your browser does not support local storage, please upgrade to latest browser");return false}}function LoadFromLocalStorage(a,b){var c=window.localStorage.getItem("'"+a+"'");if(c==null)return b==undefined?"":b;c=JSON.parse(c);return c.dt!=(new Date).getDate()?b==undefined?"":b:c.res}
function RemoveFromLocalStorage(a){window.localStorage.removeItem("'"+a+"'")}function ClearLocalStoreage(){if(typeof window.localStorage!="undefined")window.localStorage.clear();else throw"window.localStorage, not defined";}var UserPosition=null;function GetCurrentLocation(a){navigator&&navigator.geolocation?navigator.geolocation.getCurrentPosition(function(b){geo_success(b,a)},geo_error):error("Geolocation is not supported.")}
function geo_success(a,b){UserPosition={Lat:a.coords.latitude,Lng:a.coords.longitude};b!=undefined&&b(UserPosition)}function geo_error(a){if(a.code==1)error("The user denied the request for location information.");else if(a.code==2)error("Your location information is unavailable.");else a.code==3?error("The request to get your location timed out."):error("An unknown error occurred while requesting your location.")}function error(){}
function GetDistance(a,b,c,d){if(c=="0"||d=="0")return 0;if(typeof Number.prototype.toRad==="undefined")Number.prototype.toRad=function(){return this*Math.PI/180};var e=(parseFloat(c)-parseFloat(a)).toRad();b=(parseFloat(d)-parseFloat(b)).toRad();a=parseFloat(a).toRad();c=parseFloat(c).toRad();a=Math.sin(e/2)*Math.sin(e/2)+Math.sin(b/2)*Math.sin(b/2)*Math.cos(a)*Math.cos(c);return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function CheckCacheUpdate(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()})}function DelayedLoadJS(a){var b=document.createElement("script");b.setAttribute("src",a);b.setAttribute("type","text/javascript");document.getElementsByTagName("head")[0].appendChild(b);console.log("added")}function ValidateEmail(a){return a.match(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/)}
var _msg=null,map,CMD_HOME=0,CMD_SEARCH=1,CMD_HISTORY=2,CMD_SEARCH_IN_SITE=3,CMD_SHOW_SEL_QUES=4,CMD_ALERT=5,CMD_CHILD=6,CMD_LASTVISIT=7,M=new Mobile;function Mobile(){this.CurrentCommand=this.SelectedQuestionID=0;this.ParentID=1;this.ParentName="";this.PageNo=this.ChildID=1;this.Lang=0;this.DefaultEmailID=this.SelectedQuestion=""}Mobile.prototype.Save=function(){SaveInLS(this)};Mobile.prototype.Load=function(){LoadFromLS(this)};
function SaveInLS(a){for(var b in a)if(a[b]!=null)(typeof a[b]).toString()!="function"&&SaveInLocalStorage(b,JSON.stringify(a[b]));else RemoveFromLocalStorage(b)}function LoadFromLS(a){for(var b in a){var c=LoadFromLocalStorage(b);if(c!="undefined"&&c!="null"&&c!=null&&c!=undefined)if((typeof a[b]).toString()!="function")a[b]=c==""?c:JSON.parse(c)}}
function RunCommand(a){if(a){M.CurrentCommand=a;M.Save()}switch(M.CurrentCommand){case CMD_HOME:$.mobile.changePage("#divHome");break;case CMD_CHILD:$.mobile.changePage("#divChild");break;case CMD_SEARCH:$.mobile.changePage("#divQuesListPage");break;case CMD_HISTORY:$.mobile.changePage("#divFavouriteListPage");break;case CMD_SEARCH_IN_SITE:$.mobile.changePage("#divSearch");break;case CMD_SHOW_SEL_QUES:$.mobile.changePage("#divSelectedQuestionPage");break;case CMD_LASTVISIT:$.mobile.changePage("#divLastVisit")}return false}
var IsPostBack=false;function ChangePage(a){$(".dtl").hide();$("#"+a).show()}$(document).ready(function(){});
$(document).bind("pagechange",function(a,b){M.Load();switch(b.toPage.attr("id")){case "divHome":if(IsPostBack){M.Lang=0;M.PageNo=0;M.Save()}else IsPostBack=true;ChangePage("divHome");M.CurrentCommand=CMD_HOME;M.Save();FillLanguages();break;case "divChild":ChangePage("divChild");GetChild();break;case "divQuesListPage":ChangePage("divQuesListPage");GetQuestions();break;case "divFavouriteListPage":ChangePage("divFavouriteListPage");ShowHistory();break;case "divSearch":ChangePage("divSearch");Search();
break;case "divLastVisit":ChangePage("divLastVisit");ShowLastVisitMessage();break;case "divSelectedQuestionPage":ChangePage("divSelectedQuestionPage");ShowSelectedQuestion()}});$(document).bind("pageinit",function(){$.mobile.defaultPageTransition="none"});function GetData(a,b){$.ajax({url:"http://infonexus.in/learningzone/query.ashx?Action="+a,success:b})}function SearchFor(a){$("#divSearch").trigger("refresh");M.ReqFor=a;M.Save();RunCommand(CMD_SEARCH_ROUTE)}
function FillLanguages(){$("#divHome").show();$("#divBlank").hide();if(M.Lang!=0&&M.PageNo!=0){ShowLastVisitMessage();$("#imgLogo").attr("src","/Images/learningzone_logo_mob_1.png")}else{$("#divDefault").hide();var a=JSON.parse(LoadFromLocalStorage("tp","[]"));if(a.length==0){$("#divBlank").show();a=$(window).height();$("#divBlank").css({height:a-10});$(".emp").css({height:a/2-160});GetData("topics",function(b){SaveInLocalStorage("tp",b);DisplayTopics(JSON.parse(b))})}else DisplayTopics(a)}}
function ShowLastVisitMessage(){var a=[""];a[a.length]="<br/><table class='tbl'><tr><td class='tdl'><span><a id='aGoLast'  href='#' style='color:white'>Goto Last Visited Page</span></a></span></td></td></tr></table>";a[a.length]="<br/><table><tr><td style='text-align:center'><div class='round'>OR</div></table>";a[a.length]="<table class='tbl'><tr><td class='tdl' style='background-color: #40B149!important; border-color: #40B149!important'><a id='aGoHome'  href='#' style='color:white'>Goto Home Page</a></td></tr></table>";
$("#divLastVisitInfo").html(a.join(""));$("#divLastVisitInfo").show();$("#divHomeInfo").hide();$("#aGoHome").bind("click",function(){M.Lang=0;M.PageNo=0;M.Save();RunCommand(CMD_HOME)});$("#aGoLast").bind("click",function(){ShowAnswer(M.ParentName,M.Lang,M.PageNo)})}
function DisplayTopics(a){$("#divBlank").hide();$("#divDefault").show();$("#divLastVisitInfo").hide();$("#divHomeInfo").show();HideProcessingMessage();var b=["<table class='tbl'>"];$(a).each(function(){b[b.length]="<tr><td class='tdl'>"+this.name.substr(0,1)+"</td><td class='tdr'><a  href='#' onclick='ShowChild(\""+this.name+'",'+this.id+")'><span>"+this.name+"</span></a></td></tr>"});b[b.length]="<tr><td class='tdl'>S</td><td class='tdr'><a  href='#' onclick='RunCommand(CMD_SEARCH_IN_SITE)'><span>Search in site</span></a></td></tr>";
b[b.length]="</table>";$("#divLanguages").html(b.join(""));$("#divHome").trigger("create");$("#imgLogo").attr("src","/Images/learningzone_logo_mob_1.png");ShowHistory()}function ShowSocialButtons(){var a=[""];a[a.length]="<div class='ui-grid-a'>";a[a.length]="<div class='ui-block-a'>"+Build_Social_Button(FB_Share,"http://infonexus.in/mobile")+"</div><div class='ui-block-b'>"+Build_Social_Button(Twitter_Share,"http://infonexus.in/mobile")+"</div></div>";$("#divSocial").html(a.join(""))}
function ShowChild(a,b){M.ParentID=b;M.ParentName=a;M.Save();RunCommand(CMD_CHILD)}function GetChild(){$("#divChildList").html("<div style='padding:10px;background-color:#eee; margin-top:10px;color:rgb(151, 38, 38)'>Loading options, please wait..</div>");ShowProcessingMessage();var a=JSON.parse(LoadFromLocalStorage("ch_"+M.ParentID,"[]"));a.length==0?GetData("child&Data1="+M.ParentID,function(b){SaveInLocalStorage("ch_"+M.ParentID,b);DisplayChild(JSON.parse(b))}):DisplayChild(a)}
function DisplayChild(a){HideProcessingMessage();AddPageTitle(M.ParentName);var b=["<table class='tbl'>"];$(a).each(function(){b[b.length]="<tr><td class='tdl'>"+this.name.substr(0,1)+"</td><td class='tdr'><a  href='#' onclick='ShowAnswer(\""+this.name+'",'+this.id+",1)'><span>"+this.name+"</span></a></td></tr>"});b[b.length]="</table>";$("#divChildList").html(b.join(""));$("#divChild").trigger("create")}
function ShowAnswer(a,b,c){M.Lang=b;M.ParentName=a;M.PageNo=c;M.Save();RunCommand(CMD_SEARCH)}function GetQuestions(){ShowProcessingMessage();$("#divQuesList").html("");M.Load();var a=GetFromHistoryList(M.Lang,M.PageNo);a==-1?GetData("GetQuestions&Data1="+M.Lang+"&Data2="+M.PageNo,function(b){ShowQuestions(b);AddToHistoryList(M.Lang,M.PageNo,b)}):ShowQuestions(HistoryList[a].Data)}
function GetLanguage(a){for(var b=0;b<Languages.length;b++)if(Languages[b].ID==a)return Languages[b].Name.replace(/\_/g," ");return""}var Result=[];
function ShowQuestions(a){HideProcessingMessage();if(a!=""){Result=a=JSON.parse(a);AddPageTitle(M.ParentName+" ("+M.PageNo+")");var b=[""];b[b.length]="<div class='ui-grid-a'>";b[b.length]="<div class='ui-block-a'><a href='#' data-role='button' data-icon='bars' onclick='RunCommand(CMD_HISTORY)' data-corners='false' class='c'><span class='hidden-phone'>My List</span></a></div><div class='ui-block-b'><a href='#' data-role='button'  data-icon='search' onclick='RunCommand(CMD_SEARCH_IN_SITE)' data-corners='false' class='c' ><span class='hidden-phone'>Search</span></a></div></div>";$(a).each(function(c){b[b.length]=
this.t==0?SubjectiveTxt(c,this):MultiChoiceTxt(c,this)});b[b.length]="<div class='ui-grid-a'><div class='ui-block-a'><a href='#' "+(M.PageNo>1?"style='background-color:#9B9797'":"class='ui-disabled'")+" data-role='button' data-theme='b' onclick='ShowAnswer(\""+M.ParentName+'",'+M.Lang+","+(M.PageNo-1)+")'>Prev</a></div><div class='ui-block-b'><a href='#' data-role='button' data-theme='b' onclick='ShowAnswer(\""+M.ParentName+'",'+M.Lang+","+(M.PageNo+1)+")'>Next</a></div></div>";$("#divQuesList").html(b.join(""));
$("#divQuesList").trigger("create");AddClientOptions()}}function SubjectiveTxt(a,b){var c=[""];c[c.length]="<div class='mya'>";c[c.length]="<p class='q'>"+(a+1)+". "+b.q+"</p>";c[c.length]="<div class='an'>"+b.a+"</div>";c[c.length]="<div data-id='"+a+"' class='qa'></div>";c[c.length]="</div>";return c.join("")}
function MultiChoiceTxt(a,b){var c=[""];c[c.length]="<div class='mya'>";c[c.length]="<p class='q'>"+(a+1)+". "+b.q+"</p>";c[c.length]="<div class='an'>";c[c.length]="<ol class='olopt'>";c[c.length]="<li>"+b.op1;c[c.length]="<li>"+b.op2;c[c.length]="<li>"+b.op3;if(b.op4!="")c[c.length]="<li>"+b.op4;if(b.op5!="")c[c.length]="<li>"+b.op5;c[c.length]="</ol>";c[c.length]="<div class='oa'><span class='oas'>Answer : </span><span class='oam'>"+b.a+"</span></div>";c[c.length]="</div>";c[c.length]="<div data-id='"+
a+"' class='qa'></div>";c[c.length]="</div>";return c.join("")}function AddPageTitle(a){$(".lblHeader").text(a)}String.prototype.startsWith=function(a){return this.substr(0,a.length)==a};function NoData(a){if(a==undefined)return true;if(a.length==0)return true}function ShowProcessingMessage(){$.mobile.loading("show",{text:"Loading..",textVisible:true,theme:"a",textonly:false,html:""})}function HideProcessingMessage(){$.mobile.loading("hide")}var _alerttimer=null;
function ShowAlert(){_alerttimer!=null&&window.clearTimeout(_alerttimer);if(_msg!=null){$(".lblHeader").text(_msg.header);$("#divMsg").html(_msg.msg)}_alerttimer=window.setTimeout(function(){$(".ui-dialog").dialog("close")},3E3)}var FavList=[];function SaveFavList(){SaveInLocalStorage("Favs",JSON.stringify(FavList));ShowFav()}function FoundIndexInFav(a){for(var b=JSON.parse(LoadFromLocalStorage("L_History","[]")),c=0;c<b.length;c++)if(b[c].id==Result[a].id&&b[c].t==Result[a].t)return c;return-1}
function RemoveFromFav(a){ShowPopup("Removed from Favorite list");a==-1?FavList.length=0:FavList.splice(a,1);SaveFavList();AddClientOptions();return false}
function AddClientOptions(){var a="divQuesList";switch(M.CurrentCommand){case CMD_SHOW_SEL_QUES:case CMD_SEARCH_IN_SITE:a="divSelectedQuestion"}$(".qa",$("#"+a)).each(function(){var b=$(this).data("id");favindex=FoundIndexInFav(b);favindex==-1?$(this).html("<a href='#' class='qadd add'  data-id='"+b+"' >Add</a>"):$(this).html("<a href='#' class='qadd rem' data-id='"+favindex+"' >Remove</a>")});$("#"+a).trigger("create");$("#"+a+" .add").bind("click",function(){var b=$(this).data("id");AddToFavourites(Result[b]);
AddClientOptions()});$("#"+a+" .rem").bind("click",function(){var b=$(this).data("id");RemoveFavourite(b);AddClientOptions()})}function ShowPopup(a){$("#popupMenu").show();$("#popupMenu").popup();$("#popupContent").text(a);$("#popupMenu").trigger("create");$("#popupContent").show();$("#popupMenu").popup("open");setTimeout(function(){$("#popupMenu").popup("close")},2E3)}History=[];
function ShowHistory(){AddPageTitle("Topics");History=JSON.parse(LoadFromLocalStorage("L_History","[]"));var a=[""];if(History.length==0){a[a.length]="<div class='mya'>";a[a.length]="<p class='q'>No record in history</p>";a[a.length]="<div class='an'>Please view questions and add them to your favorite list</div>";a[a.length]="</div>";$("#divFavouriteList").html(a.join(""));$("#divFavouriteList").trigger("create");$("#HistoryOnMainPage").html("")}else{a[a.length]="<h3 class='ml'>My List</h3>";var b=
0;$(History).each(function(d){var e=true;if(d>4&&M.CurrentCommand==CMD_HOME)e=false;if(e){++b;a[a.length]="<div class='mya'>";a[a.length]="<h2 class='al cur-pointer' data-index='"+d+"'><table><tr><td><b>"+this.q+"</b></td><td style='width:10px'><a href='#' class='qadd1 rem' onclick='RemoveFavourite("+d+")'>Del</a></td></table></h2>";if(this.t==0)a[a.length]="<div class='an' id='an_"+d+"' style='display:none'>"+this.a+"</div>";else{a[a.length]="<div class='an' id='an_"+d+"' style='display:none'>";
a[a.length]="<ol class='olopt'>";a[a.length]="<li>"+this.op1;a[a.length]="<li>"+this.op2;a[a.length]="<li>"+this.op3;if(this.op4!="")a[a.length]="<li>"+this.op4;if(this.op5!="")a[a.length]="<li>"+this.op5;a[a.length]="</ol>";a[a.length]="<br/>Answer : <b>"+this.a+"</b></div>"}a[a.length]="</div>";a[a.length]=""}});var c="divFavouriteList";if(M.CurrentCommand==CMD_HOME){if(History.length>5)a[a.length]="<a class='lim' href='#' onclick='RunCommand(CMD_HISTORY)'><h2>View "+(History.length-5)+" More</h2></a>";
c="HistoryOnMainPage"}else AddPageTitle("My List");$("#"+c).html(a.join(""));$("#"+c+" .al").bind("click",function(){var d=$(this).data("index");$("#an_"+d).toggle()});$("#"+c).trigger("create")}}function RemoveFavourite(a){History.splice(a,1);SaveInLocalStorage("L_History",JSON.stringify(History));History=JSON.parse(LoadFromLocalStorage("L_History","[]"));if(M.CurrentCommand==CMD_HOME)ShowHistory();else M.CurrentCommand==CMD_HISTORY&&RunCommand(CMD_HISTORY)}
function AddToFavourites(a){if(GetFromHistory(a.id,a.t)==-1){History[History.length]=a;SaveInLocalStorage("L_History",JSON.stringify(History));History=JSON.parse(LoadFromLocalStorage("L_History","[]"))}}var HistoryList=[];
function AddToHistoryList(a,b,c){if(GetFromHistoryList(a,b)==-1){HistoryList.length==50&&HistoryList.splice(1,9);HistoryList[HistoryList.length]={LangID:a,PageNo:b,Data:c};SaveInLocalStorage("L_HistoryList",JSON.stringify(HistoryList));HistoryList=JSON.parse(LoadFromLocalStorage("L_HistoryList","[]"))}}function GetFromHistoryList(a,b){for(var c=0;c<HistoryList.length;c++)if(HistoryList[c].LangID==a&&HistoryList[c].PageNo==b)return c;return-1}
function GetFromHistory(a,b){for(var c=0;c<History.length;c++)if(History[c].id==a&&History[c].t==b)return c;return-1}function GetSelectedQuestion(){AddPageTitle("Searched Question");M.Load();var a=GetFromHistory(M.SelectedQuestion);a==-1?GetData("http://infonexus.in/learningzone/query.ashx?Action=GetSelectedQuestion&Data1="+M.SelectedQuestion,function(b){b=NoData(b)?"[]":b;b=JSON.parse(b);ShowSelectedQuestion(b)}):ShowQuestions(JSON.parse(HistoryList[a].Data))}
function ShowSelectedQuestion(a){Result[0]=a;var b=[""];b[b.length]="<ul data-role='listview' data-inset='true' >";b[b.length]="<li class='q' data-role='list-divider'>1. "+a.Question+"<span data-id='0' class='qa'></span></li>";b[b.length]="<li data-theme='a' data-icon='false' ><a href='#' ><p>"+a.Answer+"</p></a></li>";b[b.length]="</ul>";$("#divSelectedQuestion").html(b.join(""));$("#divSelectedQuestion").trigger("create");AddClientOptions()}
function SendEmail(){var a="";M.CurrentCommand==CMD_HISTORY?$(History).each(function(){a+=this.ID+"-0^"}):$(Result).each(function(){a+=this.ID+"-0^"});var b="<span style='color:white'>eMail this page</span><br/><input type='text' id='txtTo' placeholder='email id' />";b+="<a href='#' data-role='button' data-icon='arrow-r' data-iconpos='right' data-inline='true' data-theme='b' id='btnsendmail'>Send</a>";b+="<br/><span style='color:white' id='msg'></span>";$("#popupMenu").popup();$("#popupContent").html(b);
$("#txtTo").val(M.DefaultEmailID);$("#popupContent").show();$("#popupMenu").show();$("#popupMenu").popup("open");$("#popupMenu").trigger("create");$("#popupContent #btnsendmail").bind("click",function(){var c=$("#txtTo").val();if(c==""||!ValidateEmail(c))$("#popupContent #msg").text("Please enter a valid email ID.");else{$.post("http://infonexus.in/learningzone/query.ashx?Action=SM",{To:c,Data:a},function(){});$("#popupContent #msg").text("Mail sent, please check your inbox/spam");setTimeout(function(){$("#popupMenu").popup("close")},
2E3);M.DefaultEmailID=$("#txtTo").val();M.Save()}})}
function Search(){$("#divSearch").trigger("create");$("#txtSearch").focus();$("#btnsearch").bind("click",function(){var a=$("#txtSearch").val().trim();if(a=="")$("#divSearchResult").html("enter some text to search");else{ShowProcessingMessage();GetData("Search&Data1="+a,function(b){HideProcessingMessage();var c=[""];c[c.length]="<h3 class='ml'>Search Result</h3>";if(b=="[]"){c[c.length]="<div class='mya'>";c[c.length]="<p class='q'>No Results found</p>";c[c.length]="</div>"}else{var d=JSON.parse(b);
$(d).each(function(e){c[c.length]="<div class='mya'>";c[c.length]="<p class='q' data-index='"+e+"'>"+this.q+"</p>";c[c.length]="</div>"})}$("#divSearchResult").html(c.join(""));$("#divSearchResult").trigger("create");b!="[]"&&$("#divSearchResult .q").bind("click",function(){var e=$(this).data("index");e=d[e];M.SelectedQuestionID=e.id;M.Lang=e.l;M.Save();RunCommand(CMD_SHOW_SEL_QUES)})})}})}
function ShowSelectedQuestion(){var a=M.SelectedQuestionID,b=M.Lang;AddPageTitle("Selected Questions");ShowProcessingMessage();GetData("GetSelectedQuestion&Data1="+a+"&Data2="+b,function(c){if(NoData(c))$("#divSelectedQuestion").html("No result found");else{HideProcessingMessage();c=JSON.parse(c);Result[0]=c;var d=[""];d[d.length]=c.t==0?SubjectiveTxt(0,c):MultiChoiceTxt(0,c);d[d.length]="<br/><a href='#' data-role='button' id='btnAllCat' onclick='ShowAnswer(\""+c.n+'",'+c.l+",1)' data-corners='false' class='c btn-block'>All questions in this category</a>";
$("#divSelectedQuestion").html(d.join(""));$("#divSelectedQuestion").trigger("create");AddClientOptions()}})};
